# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StocksDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 pod 'Alamofire'
pod 'SwiftyJSON'
use_frameworks!

  # Pods for StocksDemo

  target 'StocksDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StocksDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
